### ISSUE TITLE
is:issue is:open 你好，我的路由器也是sft1200，我无法使用actions自动构建，可以发我一份编译好的固件吗，谢谢大佬，邮件：z1723317366@outlook.com 

### ISSUE THREAD

**Issue by zhangyao-20021223** [201821143044/Actions-SFT1200-OpenWrt#1]
is:issue is:open 你好，我的路由器也是sft1200，我无法使用actions自动构建，可以发我一份编译好的固件吗，谢谢大佬，邮件：z1723317366@outlook.com

**Comment by 201821143044** [comment]
https://myqqq.lanzouq.com/b0elmxane
密码:4e2z
